/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace AttestationRegistry {
  export type AttestationStruct = {
    target: AddressLike;
    score: BigNumberish;
    verdict: BigNumberish;
    findingsHash: BigNumberish;
    reportUri: string;
    payloadHash: BytesLike;
    attestedAt: BigNumberish;
    blockNumber: BigNumberish;
  };

  export type AttestationStructOutput = [
    target: string,
    score: bigint,
    verdict: bigint,
    findingsHash: bigint,
    reportUri: string,
    payloadHash: string,
    attestedAt: bigint,
    blockNumber: bigint
  ] & {
    target: string;
    score: bigint;
    verdict: bigint;
    findingsHash: bigint;
    reportUri: string;
    payloadHash: string;
    attestedAt: bigint;
    blockNumber: bigint;
  };
}

export interface AttestationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "activeVerifierCount"
      | "addVerifier"
      | "attest"
      | "attestations"
      | "getAttestation"
      | "getHistory"
      | "history"
      | "isVerifier"
      | "removeVerifier"
      | "verifier"
      | "verifierCount"
      | "verifierList"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Attested" | "VerifierAdded" | "VerifierRemoved"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "activeVerifierCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "attest",
    values: [
      AddressLike,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      string,
      BytesLike
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "attestations",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttestation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "history",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "verifierCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "verifierList",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "activeVerifierCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "attest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getHistory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "history", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isVerifier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "verifierCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifierList",
    data: BytesLike
  ): Result;
}

export namespace AttestedEvent {
  export type InputTuple = [
    target: AddressLike,
    score: BigNumberish,
    verdict: BigNumberish,
    findingsHash: BigNumberish,
    reportUri: string,
    payloadHash: BytesLike,
    attestedAt: BigNumberish
  ];
  export type OutputTuple = [
    target: string,
    score: bigint,
    verdict: bigint,
    findingsHash: bigint,
    reportUri: string,
    payloadHash: string,
    attestedAt: bigint
  ];
  export interface OutputObject {
    target: string;
    score: bigint;
    verdict: bigint;
    findingsHash: bigint;
    reportUri: string;
    payloadHash: string;
    attestedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierAddedEvent {
  export type InputTuple = [v: AddressLike];
  export type OutputTuple = [v: string];
  export interface OutputObject {
    v: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierRemovedEvent {
  export type InputTuple = [v: AddressLike];
  export type OutputTuple = [v: string];
  export interface OutputObject {
    v: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AttestationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AttestationRegistry;
  waitForDeployment(): Promise<this>;

  interface: AttestationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  activeVerifierCount: TypedContractMethod<[], [bigint], "view">;

  addVerifier: TypedContractMethod<[v: AddressLike], [void], "nonpayable">;

  attest: TypedContractMethod<
    [
      target: AddressLike,
      score: BigNumberish,
      verdict: BigNumberish,
      findingsHash: BigNumberish,
      reportUri: string,
      payloadHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;

  attestations: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, string, string, bigint, bigint] & {
        target: string;
        score: bigint;
        verdict: bigint;
        findingsHash: bigint;
        reportUri: string;
        payloadHash: string;
        attestedAt: bigint;
        blockNumber: bigint;
      }
    ],
    "view"
  >;

  getAttestation: TypedContractMethod<
    [target: AddressLike],
    [AttestationRegistry.AttestationStructOutput],
    "view"
  >;

  getHistory: TypedContractMethod<
    [target: AddressLike],
    [AttestationRegistry.AttestationStructOutput[]],
    "view"
  >;

  history: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, string, string, bigint, bigint] & {
        target: string;
        score: bigint;
        verdict: bigint;
        findingsHash: bigint;
        reportUri: string;
        payloadHash: string;
        attestedAt: bigint;
        blockNumber: bigint;
      }
    ],
    "view"
  >;

  isVerifier: TypedContractMethod<[arg0: AddressLike], [boolean], "view">;

  removeVerifier: TypedContractMethod<[v: AddressLike], [void], "nonpayable">;

  verifier: TypedContractMethod<[], [string], "view">;

  verifierCount: TypedContractMethod<[], [bigint], "view">;

  verifierList: TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "activeVerifierCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "addVerifier"
  ): TypedContractMethod<[v: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "attest"
  ): TypedContractMethod<
    [
      target: AddressLike,
      score: BigNumberish,
      verdict: BigNumberish,
      findingsHash: BigNumberish,
      reportUri: string,
      payloadHash: BytesLike
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "attestations"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, string, string, bigint, bigint] & {
        target: string;
        score: bigint;
        verdict: bigint;
        findingsHash: bigint;
        reportUri: string;
        payloadHash: string;
        attestedAt: bigint;
        blockNumber: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAttestation"
  ): TypedContractMethod<
    [target: AddressLike],
    [AttestationRegistry.AttestationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getHistory"
  ): TypedContractMethod<
    [target: AddressLike],
    [AttestationRegistry.AttestationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "history"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, string, string, bigint, bigint] & {
        target: string;
        score: bigint;
        verdict: bigint;
        findingsHash: bigint;
        reportUri: string;
        payloadHash: string;
        attestedAt: bigint;
        blockNumber: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "isVerifier"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "removeVerifier"
  ): TypedContractMethod<[v: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "verifierCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "verifierList"
  ): TypedContractMethod<[arg0: BigNumberish], [string], "view">;

  getEvent(
    key: "Attested"
  ): TypedContractEvent<
    AttestedEvent.InputTuple,
    AttestedEvent.OutputTuple,
    AttestedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierAdded"
  ): TypedContractEvent<
    VerifierAddedEvent.InputTuple,
    VerifierAddedEvent.OutputTuple,
    VerifierAddedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierRemoved"
  ): TypedContractEvent<
    VerifierRemovedEvent.InputTuple,
    VerifierRemovedEvent.OutputTuple,
    VerifierRemovedEvent.OutputObject
  >;

  filters: {
    "Attested(address,uint96,uint8,uint64,string,bytes32,uint64)": TypedContractEvent<
      AttestedEvent.InputTuple,
      AttestedEvent.OutputTuple,
      AttestedEvent.OutputObject
    >;
    Attested: TypedContractEvent<
      AttestedEvent.InputTuple,
      AttestedEvent.OutputTuple,
      AttestedEvent.OutputObject
    >;

    "VerifierAdded(address)": TypedContractEvent<
      VerifierAddedEvent.InputTuple,
      VerifierAddedEvent.OutputTuple,
      VerifierAddedEvent.OutputObject
    >;
    VerifierAdded: TypedContractEvent<
      VerifierAddedEvent.InputTuple,
      VerifierAddedEvent.OutputTuple,
      VerifierAddedEvent.OutputObject
    >;

    "VerifierRemoved(address)": TypedContractEvent<
      VerifierRemovedEvent.InputTuple,
      VerifierRemovedEvent.OutputTuple,
      VerifierRemovedEvent.OutputObject
    >;
    VerifierRemoved: TypedContractEvent<
      VerifierRemovedEvent.InputTuple,
      VerifierRemovedEvent.OutputTuple,
      VerifierRemovedEvent.OutputObject
    >;
  };
}
