/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as mocks from "./mocks";
export type { mocks };
export type { AttestationRegistry } from "./AttestationRegistry";
export type { IssuanceRegistry } from "./IssuanceRegistry";
export type { RevenueDistributor } from "./RevenueDistributor";
export type { RwaToken } from "./RwaToken";
export type { SecondaryMarket } from "./SecondaryMarket";
