/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export declare namespace IssuanceRegistry {
  export type IssuanceStruct = {
    id: BigNumberish;
    issuer: AddressLike;
    token: AddressLike;
    distributor: AddressLike;
    pricePerToken: BigNumberish;
    docsUri: string;
    listedAt: BigNumberish;
    blockNumber: BigNumberish;
  };

  export type IssuanceStructOutput = [
    id: bigint,
    issuer: string,
    token: string,
    distributor: string,
    pricePerToken: bigint,
    docsUri: string,
    listedAt: bigint,
    blockNumber: bigint
  ] & {
    id: bigint;
    issuer: string;
    token: string;
    distributor: string;
    pricePerToken: bigint;
    docsUri: string;
    listedAt: bigint;
    blockNumber: bigint;
  };
}

export interface IssuanceRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attestations"
      | "count"
      | "getAll"
      | "getIssuance"
      | "getIssuanceByToken"
      | "issue"
      | "setVerifier"
      | "verifier"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Issued" | "VerifierChanged"): EventFragment;

  encodeFunctionData(
    functionFragment: "attestations",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "count", values?: undefined): string;
  encodeFunctionData(functionFragment: "getAll", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getIssuance",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getIssuanceByToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issue",
    values: [AddressLike, AddressLike, AddressLike, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "attestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "count", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getAll", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getIssuance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getIssuanceByToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "issue", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
}

export namespace IssuedEvent {
  export type InputTuple = [
    id: BigNumberish,
    issuer: AddressLike,
    token: AddressLike,
    distributor: AddressLike,
    pricePerToken: BigNumberish,
    docsUri: string
  ];
  export type OutputTuple = [
    id: bigint,
    issuer: string,
    token: string,
    distributor: string,
    pricePerToken: bigint,
    docsUri: string
  ];
  export interface OutputObject {
    id: bigint;
    issuer: string;
    token: string;
    distributor: string;
    pricePerToken: bigint;
    docsUri: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierChangedEvent {
  export type InputTuple = [oldVerifier: AddressLike, newVerifier: AddressLike];
  export type OutputTuple = [oldVerifier: string, newVerifier: string];
  export interface OutputObject {
    oldVerifier: string;
    newVerifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IssuanceRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IssuanceRegistry;
  waitForDeployment(): Promise<this>;

  interface: IssuanceRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attestations: TypedContractMethod<[], [string], "view">;

  count: TypedContractMethod<[], [bigint], "view">;

  getAll: TypedContractMethod<
    [],
    [IssuanceRegistry.IssuanceStructOutput[]],
    "view"
  >;

  getIssuance: TypedContractMethod<
    [id: BigNumberish],
    [IssuanceRegistry.IssuanceStructOutput],
    "view"
  >;

  getIssuanceByToken: TypedContractMethod<
    [token: AddressLike],
    [IssuanceRegistry.IssuanceStructOutput],
    "view"
  >;

  issue: TypedContractMethod<
    [
      issuer_: AddressLike,
      token: AddressLike,
      distributor: AddressLike,
      pricePerToken: BigNumberish,
      docsUri: string
    ],
    [bigint],
    "nonpayable"
  >;

  setVerifier: TypedContractMethod<
    [newVerifier: AddressLike],
    [void],
    "nonpayable"
  >;

  verifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attestations"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "count"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getAll"
  ): TypedContractMethod<[], [IssuanceRegistry.IssuanceStructOutput[]], "view">;
  getFunction(
    nameOrSignature: "getIssuance"
  ): TypedContractMethod<
    [id: BigNumberish],
    [IssuanceRegistry.IssuanceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getIssuanceByToken"
  ): TypedContractMethod<
    [token: AddressLike],
    [IssuanceRegistry.IssuanceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "issue"
  ): TypedContractMethod<
    [
      issuer_: AddressLike,
      token: AddressLike,
      distributor: AddressLike,
      pricePerToken: BigNumberish,
      docsUri: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setVerifier"
  ): TypedContractMethod<[newVerifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Issued"
  ): TypedContractEvent<
    IssuedEvent.InputTuple,
    IssuedEvent.OutputTuple,
    IssuedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierChanged"
  ): TypedContractEvent<
    VerifierChangedEvent.InputTuple,
    VerifierChangedEvent.OutputTuple,
    VerifierChangedEvent.OutputObject
  >;

  filters: {
    "Issued(uint64,address,address,address,uint256,string)": TypedContractEvent<
      IssuedEvent.InputTuple,
      IssuedEvent.OutputTuple,
      IssuedEvent.OutputObject
    >;
    Issued: TypedContractEvent<
      IssuedEvent.InputTuple,
      IssuedEvent.OutputTuple,
      IssuedEvent.OutputObject
    >;

    "VerifierChanged(address,address)": TypedContractEvent<
      VerifierChangedEvent.InputTuple,
      VerifierChangedEvent.OutputTuple,
      VerifierChangedEvent.OutputObject
    >;
    VerifierChanged: TypedContractEvent<
      VerifierChangedEvent.InputTuple,
      VerifierChangedEvent.OutputTuple,
      VerifierChangedEvent.OutputObject
    >;
  };
}
