/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface SecondaryMarketInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buy"
      | "issuer"
      | "price"
      | "priceHistory"
      | "priceHistoryCount"
      | "quoteTokenOut"
      | "quoteUsdtOut"
      | "reserveToken"
      | "reserveUsdt"
      | "seed"
      | "sell"
      | "token"
      | "totalBuyVolume"
      | "totalSellVolume"
      | "usdt"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "Seeded" | "Swapped"): EventFragment;

  encodeFunctionData(functionFragment: "buy", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "issuer", values?: undefined): string;
  encodeFunctionData(functionFragment: "price", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "priceHistory",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "priceHistoryCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "quoteTokenOut",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteUsdtOut",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "reserveToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "reserveUsdt",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "seed",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "sell", values: [BigNumberish]): string;
  encodeFunctionData(functionFragment: "token", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalBuyVolume",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalSellVolume",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "usdt", values?: undefined): string;

  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "issuer", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "price", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "priceHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "priceHistoryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteTokenOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "quoteUsdtOut",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "reserveUsdt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "seed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "sell", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "token", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalBuyVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalSellVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "usdt", data: BytesLike): Result;
}

export namespace SeededEvent {
  export type InputTuple = [
    by: AddressLike,
    tokenAmount: BigNumberish,
    usdtAmount: BigNumberish
  ];
  export type OutputTuple = [
    by: string,
    tokenAmount: bigint,
    usdtAmount: bigint
  ];
  export interface OutputObject {
    by: string;
    tokenAmount: bigint;
    usdtAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace SwappedEvent {
  export type InputTuple = [
    by: AddressLike,
    isBuy: boolean,
    tokenAmount: BigNumberish,
    usdtAmount: BigNumberish
  ];
  export type OutputTuple = [
    by: string,
    isBuy: boolean,
    tokenAmount: bigint,
    usdtAmount: bigint
  ];
  export interface OutputObject {
    by: string;
    isBuy: boolean;
    tokenAmount: bigint;
    usdtAmount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface SecondaryMarket extends BaseContract {
  connect(runner?: ContractRunner | null): SecondaryMarket;
  waitForDeployment(): Promise<this>;

  interface: SecondaryMarketInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buy: TypedContractMethod<[usdtIn: BigNumberish], [bigint], "nonpayable">;

  issuer: TypedContractMethod<[], [string], "view">;

  price: TypedContractMethod<[], [bigint], "view">;

  priceHistory: TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, bigint, bigint] & { ts: bigint; price: bigint; kind: bigint }],
    "view"
  >;

  priceHistoryCount: TypedContractMethod<[], [bigint], "view">;

  quoteTokenOut: TypedContractMethod<[usdtIn: BigNumberish], [bigint], "view">;

  quoteUsdtOut: TypedContractMethod<[tokenIn: BigNumberish], [bigint], "view">;

  reserveToken: TypedContractMethod<[], [bigint], "view">;

  reserveUsdt: TypedContractMethod<[], [bigint], "view">;

  seed: TypedContractMethod<
    [tokenAmount: BigNumberish, usdtAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  sell: TypedContractMethod<[tokenIn: BigNumberish], [bigint], "nonpayable">;

  token: TypedContractMethod<[], [string], "view">;

  totalBuyVolume: TypedContractMethod<[], [bigint], "view">;

  totalSellVolume: TypedContractMethod<[], [bigint], "view">;

  usdt: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<[usdtIn: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "issuer"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "price"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "priceHistory"
  ): TypedContractMethod<
    [arg0: BigNumberish],
    [[bigint, bigint, bigint] & { ts: bigint; price: bigint; kind: bigint }],
    "view"
  >;
  getFunction(
    nameOrSignature: "priceHistoryCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "quoteTokenOut"
  ): TypedContractMethod<[usdtIn: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "quoteUsdtOut"
  ): TypedContractMethod<[tokenIn: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "reserveToken"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "reserveUsdt"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "seed"
  ): TypedContractMethod<
    [tokenAmount: BigNumberish, usdtAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "sell"
  ): TypedContractMethod<[tokenIn: BigNumberish], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "token"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalBuyVolume"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "totalSellVolume"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "usdt"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Seeded"
  ): TypedContractEvent<
    SeededEvent.InputTuple,
    SeededEvent.OutputTuple,
    SeededEvent.OutputObject
  >;
  getEvent(
    key: "Swapped"
  ): TypedContractEvent<
    SwappedEvent.InputTuple,
    SwappedEvent.OutputTuple,
    SwappedEvent.OutputObject
  >;

  filters: {
    "Seeded(address,uint256,uint256)": TypedContractEvent<
      SeededEvent.InputTuple,
      SeededEvent.OutputTuple,
      SeededEvent.OutputObject
    >;
    Seeded: TypedContractEvent<
      SeededEvent.InputTuple,
      SeededEvent.OutputTuple,
      SeededEvent.OutputObject
    >;

    "Swapped(address,bool,uint256,uint256)": TypedContractEvent<
      SwappedEvent.InputTuple,
      SwappedEvent.OutputTuple,
      SwappedEvent.OutputObject
    >;
    Swapped: TypedContractEvent<
      SwappedEvent.InputTuple,
      SwappedEvent.OutputTuple,
      SwappedEvent.OutputObject
    >;
  };
}
