/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace AttestationRegistry {
  export type AttestationStruct = {
    target: AddressLike;
    score: BigNumberish;
    verdict: BigNumberish;
    findingsHash: BigNumberish;
    reportUri: string;
    attestedAt: BigNumberish;
    blockNumber: BigNumberish;
  };

  export type AttestationStructOutput = [
    target: string,
    score: bigint,
    verdict: bigint,
    findingsHash: bigint,
    reportUri: string,
    attestedAt: bigint,
    blockNumber: bigint
  ] & {
    target: string;
    score: bigint;
    verdict: bigint;
    findingsHash: bigint;
    reportUri: string;
    attestedAt: bigint;
    blockNumber: bigint;
  };
}

export interface AttestationRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "attest"
      | "attestations"
      | "getAttestation"
      | "getHistory"
      | "history"
      | "setVerifier"
      | "verifier"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "Attested" | "VerifierChanged"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "attest",
    values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, string]
  ): string;
  encodeFunctionData(
    functionFragment: "attestations",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getAttestation",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHistory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "history",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setVerifier",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "verifier", values?: undefined): string;

  decodeFunctionResult(functionFragment: "attest", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "attestations",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAttestation",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getHistory", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "history", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setVerifier",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "verifier", data: BytesLike): Result;
}

export namespace AttestedEvent {
  export type InputTuple = [
    target: AddressLike,
    score: BigNumberish,
    verdict: BigNumberish,
    findingsHash: BigNumberish,
    reportUri: string,
    attestedAt: BigNumberish
  ];
  export type OutputTuple = [
    target: string,
    score: bigint,
    verdict: bigint,
    findingsHash: bigint,
    reportUri: string,
    attestedAt: bigint
  ];
  export interface OutputObject {
    target: string;
    score: bigint;
    verdict: bigint;
    findingsHash: bigint;
    reportUri: string;
    attestedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace VerifierChangedEvent {
  export type InputTuple = [oldVerifier: AddressLike, newVerifier: AddressLike];
  export type OutputTuple = [oldVerifier: string, newVerifier: string];
  export interface OutputObject {
    oldVerifier: string;
    newVerifier: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface AttestationRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): AttestationRegistry;
  waitForDeployment(): Promise<this>;

  interface: AttestationRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  attest: TypedContractMethod<
    [
      target: AddressLike,
      score: BigNumberish,
      verdict: BigNumberish,
      findingsHash: BigNumberish,
      reportUri: string
    ],
    [bigint],
    "nonpayable"
  >;

  attestations: TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, string, bigint, bigint] & {
        target: string;
        score: bigint;
        verdict: bigint;
        findingsHash: bigint;
        reportUri: string;
        attestedAt: bigint;
        blockNumber: bigint;
      }
    ],
    "view"
  >;

  getAttestation: TypedContractMethod<
    [target: AddressLike],
    [AttestationRegistry.AttestationStructOutput],
    "view"
  >;

  getHistory: TypedContractMethod<
    [target: AddressLike],
    [AttestationRegistry.AttestationStructOutput[]],
    "view"
  >;

  history: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, string, bigint, bigint] & {
        target: string;
        score: bigint;
        verdict: bigint;
        findingsHash: bigint;
        reportUri: string;
        attestedAt: bigint;
        blockNumber: bigint;
      }
    ],
    "view"
  >;

  setVerifier: TypedContractMethod<
    [newVerifier: AddressLike],
    [void],
    "nonpayable"
  >;

  verifier: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "attest"
  ): TypedContractMethod<
    [
      target: AddressLike,
      score: BigNumberish,
      verdict: BigNumberish,
      findingsHash: BigNumberish,
      reportUri: string
    ],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "attestations"
  ): TypedContractMethod<
    [arg0: AddressLike],
    [
      [string, bigint, bigint, bigint, string, bigint, bigint] & {
        target: string;
        score: bigint;
        verdict: bigint;
        findingsHash: bigint;
        reportUri: string;
        attestedAt: bigint;
        blockNumber: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAttestation"
  ): TypedContractMethod<
    [target: AddressLike],
    [AttestationRegistry.AttestationStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getHistory"
  ): TypedContractMethod<
    [target: AddressLike],
    [AttestationRegistry.AttestationStructOutput[]],
    "view"
  >;
  getFunction(
    nameOrSignature: "history"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [string, bigint, bigint, bigint, string, bigint, bigint] & {
        target: string;
        score: bigint;
        verdict: bigint;
        findingsHash: bigint;
        reportUri: string;
        attestedAt: bigint;
        blockNumber: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "setVerifier"
  ): TypedContractMethod<[newVerifier: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "verifier"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "Attested"
  ): TypedContractEvent<
    AttestedEvent.InputTuple,
    AttestedEvent.OutputTuple,
    AttestedEvent.OutputObject
  >;
  getEvent(
    key: "VerifierChanged"
  ): TypedContractEvent<
    VerifierChangedEvent.InputTuple,
    VerifierChangedEvent.OutputTuple,
    VerifierChangedEvent.OutputObject
  >;

  filters: {
    "Attested(address,uint96,uint8,uint64,string,uint64)": TypedContractEvent<
      AttestedEvent.InputTuple,
      AttestedEvent.OutputTuple,
      AttestedEvent.OutputObject
    >;
    Attested: TypedContractEvent<
      AttestedEvent.InputTuple,
      AttestedEvent.OutputTuple,
      AttestedEvent.OutputObject
    >;

    "VerifierChanged(address,address)": TypedContractEvent<
      VerifierChangedEvent.InputTuple,
      VerifierChangedEvent.OutputTuple,
      VerifierChangedEvent.OutputObject
    >;
    VerifierChanged: TypedContractEvent<
      VerifierChangedEvent.InputTuple,
      VerifierChangedEvent.OutputTuple,
      VerifierChangedEvent.OutputObject
    >;
  };
}
