/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AttestationRegistry } from "./AttestationRegistry";
export * as factories from "./factories";
export { AttestationRegistry__factory } from "./factories/AttestationRegistry__factory";
